baseURL = "https://www.example.com"
languageCode = "en-us"
title = "My Digital Garden"
copyright = "Haoyuehx ©"


[params]
  name = "HaoyuehxのBlog"
  description = "Red panda living in the eastern Himalayas."
  initials = "Haoyue"
  googleAnalytics = ""

  [[params.social]]
    name = "Bilibili"
    link = "https://space.bilibili.com/3494363854276671"
    icon = "fab fa-bilibili"

  [[params.social]]
    name = "QQ" 
    link = "#"
    icon = "fab fa-qq"

  [[params.social]]
    name = "Weixin" 
    link = "#"
    icon = "fab fa-weixin"

  [[params.social]]
    name = "Telegram" 
    link = "https://t.me/haoyuehx"
    icon = "fab fa-telegram"

  [[params.social]]
    name = "Mail" 
    link = "#"
    icon = "fas fa-envelope"

  [[params.social]]
    name = "Twitter"
    link = "https://x.com/Haoyuehx"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Zhihu"
    link = "https://www.zhihu.com/people/4skcf3"
    icon = "fab fa-zhihu"

  [[params.social]]
    name = "Github"
    link = "https://github.com/Haoyuehexi"
    icon = "fab fa-github"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'